flowchart TB
    ES["Estudiante"]
    BI["Bibliotecario"]
    subgraph APP["BiblioUNSA — Monolito modular (un solo despliegue)"]
        API["Capa de presentación: API REST + web responsive"]
        M1["Autenticación<br/>y autorización"]
        M2["Catálogo e<br/>inventario"]
        M3["Reservas"]
        M4["Préstamos<br/>(carné QR)"]
        M5["Multas"]
        M6["Notificaciones"]
        INF["Capa de infraestructura: repositorios y adaptadores externos"]
    end
    DB[("PostgreSQL<br/>(un esquema por módulo)")]
    IDP["Proveedor de identidad<br/>del correo institucional (OIDC)"]
    ACA["API del Sistema Académico"]
    SMTP["Servicio de correo (SMTP)"]
    ES & BI --> API
    API --> M1 & M2 & M3 & M4 & M5 & M6
    M3 -->|"consulta disponibilidad"| M2
    M4 -->|"genera multas"| M5
    M3 & M4 & M5 -->|"avisos"| M6
    M1 & M2 & M3 & M4 & M5 & M6 --> INF
    INF --> DB
    INF --> IDP
    INF --> ACA
    INF --> SMTP
    classDef mod fill:#E8F5E9,stroke:#2E7D32,color:#000
    classDef ext fill:#F2F2F2,stroke:#7F7F7F,color:#000,stroke-dasharray: 4 3
    classDef usr fill:#FDEDEC,stroke:#C8310E,color:#000
    class M1,M2,M3,M4,M5,M6 mod
    class IDP,ACA,SMTP ext
    class ES,BI usr
